create table ceedo_collections.collections (
  -- NO DEFAULT. The UUID is generated by the client, and that is what makes posting
  -- idempotent (invariant #2): a retry after a dropped connection carries the same id and
  -- is recognised as a duplicate. A server-side default would mint a fresh id on every
  -- retry and issue a second receipt for one payment.
  id            uuid primary key,
  or_no         integer not null check (or_no > 0),
  booklet_id    uuid not null references ceedo_collections.booklets (id),
  collector_id  uuid not null references ceedo_collections.app_users (id),
  -- NOT NULL: every collection is recorded on a tablet. There is no office payment path
  -- (design D7), so a collection with no device is not a case to allow for, it is a bug.
  device_id     uuid not null references ceedo_collections.devices (id),
  collected_at  timestamptz not null,
  business_date date not null,
  fee_type_id   uuid not null references ceedo_collections.fee_types (id),
  -- Null for cash-only streams: parking, terminal and slaughterhouse receipts belong to
  -- no lease and settle no charge.
  lease_id      uuid references ceedo_collections.leases (id),
  payer_ref     text,
  gross_amount  numeric(14,2) not null check (gross_amount > 0),
  notes         text,
  synced_at     timestamptz,
  posted_at     timestamptz not null default now(),
  posted_by     uuid references ceedo_collections.app_users (id),
  row_version   bigint not null default 0,

  -- A serial is spent exactly once across the entire system (invariant #17). This is the
  -- ONLY mechanism that catches the same OR number recorded on two different devices --
  -- a case §6.3 of the parent spec notes a device physically cannot detect, because
  -- neither tablet can see the other's outbox.
  constraint collections_serial_spent_once unique (booklet_id, or_no)
);

create index collections_lease_idx on ceedo_collections.collections (lease_id);
create index collections_collector_date_idx
  on ceedo_collections.collections (collector_id, business_date);
create index collections_row_version_idx on ceedo_collections.collections (row_version);

create table ceedo_collections.collection_allocations (
  id            uuid primary key default gen_random_uuid(),
  collection_id uuid not null references ceedo_collections.collections (id),
  charge_id     uuid not null references ceedo_collections.charges (id),
  amount        numeric(14,2) not null check (amount > 0),
  row_version   bigint not null default 0,
  unique (collection_id, charge_id)
);

create index collection_allocations_charge_idx
  on ceedo_collections.collection_allocations (charge_id);

create table ceedo_collections.collection_lines (
  id            uuid primary key default gen_random_uuid(),
  collection_id uuid not null references ceedo_collections.collections (id),
  fee_type_id   uuid not null references ceedo_collections.fee_types (id),
  rate_class    text not null default '',
  quantity      integer not null check (quantity > 0),
  unit_rate     numeric(14,2) not null check (unit_rate >= 0),
  -- Generated, not stored independently. Quantity times rate cannot be recorded
  -- inconsistently with quantity and rate, because it is not recorded at all.
  amount        numeric(14,2) generated always as (quantity * unit_rate) stored,
  row_version   bigint not null default 0
);

create index collection_lines_collection_idx
  on ceedo_collections.collection_lines (collection_id);

create table ceedo_collections.collection_cancellations (
  id            uuid primary key default gen_random_uuid(),
  -- Unique: a receipt is cancelled once. A second cancellation is not a correction, it is
  -- a sign that something is being retried that should not be.
  collection_id uuid not null unique references ceedo_collections.collections (id),
  reason        text not null check (length(trim(reason)) > 0),
  cancelled_by  uuid not null references ceedo_collections.app_users (id),
  cancelled_at  timestamptz not null default now(),
  row_version   bigint not null default 0
);

select ceedo_collections.apply_ledger_policies('collections');
select ceedo_collections.apply_ledger_policies('collection_allocations');
select ceedo_collections.apply_ledger_policies('collection_lines');
select ceedo_collections.apply_ledger_policies('collection_cancellations');

-- Voiding a receipt is a decision someone makes, unlike the receipt itself which is
-- already immutable and actor-stamped. §11.4 wants the decision on the record.
select ceedo_collections.attach_audit('collection_cancellations');

-- Invariant #9: a collection's allocations and lines together sum to its gross_amount.
--
-- A DEFERRED constraint trigger, checked at commit rather than per statement. The parts
-- are inserted after the parent row inside one transaction, so a per-statement check
-- would fire against a collection that legitimately has no allocations yet and refuse
-- every valid post.
create or replace function ceedo_collections.assert_collection_balances()
returns trigger
language plpgsql
set search_path = ceedo_collections, pg_temp
as $$
declare
  v_gross numeric(14,2);
  v_parts numeric(14,2);
begin
  select gross_amount into v_gross
  from ceedo_collections.collections where id = new.id;

  -- The row may have been removed by a rollback between the insert and this check.
  if not found then
    return null;
  end if;

  select coalesce((select sum(amount) from ceedo_collections.collection_allocations
                    where collection_id = new.id), 0)
       + coalesce((select sum(amount) from ceedo_collections.collection_lines
                    where collection_id = new.id), 0)
    into v_parts;

  if v_parts <> v_gross then
    raise exception
      'Collection % does not balance: allocations plus lines total %, gross_amount is %',
      new.id, v_parts, v_gross
      using errcode = 'check_violation';
  end if;

  return null;
end;
$$;

create constraint trigger collections_balance
  after insert on ceedo_collections.collections
  deferrable initially deferred
  for each row execute function ceedo_collections.assert_collection_balances();
